Vagrant.configure("2") do |config|
  config.vm.box = "generic/ubuntu2204"

  # Configure Splunk Forwarder
  config.vm.define "splunk_forwarder" do |forwarder|
    forwarder.vm.hostname = "splunk-forwarder"
    forwarder.vm.provider "qemu" do |fw|
      fw.arch = "x86_64"
      fw.machine = "q35"
      fw.cpu = "qemu64"
      fw.net_device = "virtio-net-pci"
    end
    forwarder.vm.network "private_network", type: "dhcp"

    forwarder.vm.provider "qemu" do |vb|
      vb.memory = "1024"
      vb.cpus = 1
    end

    # Update host ports to avoid collisions
    forwarder.vm.network "forwarded_port", guest: 22, host: 50225, id: "ssh", auto_correct: true

    forwarder.vm.synced_folder "./splunk_files", "/vagrant/splunk_files", type: "rsync"

    forwarder.vm.provision "shell", inline: <<-SHELL
      set -euxo pipefail
      SPLUNK_FORWARDER_DEB="/vagrant/splunk_files/splunkforwarder-9.4.0-6b4ebe426ca6-linux-amd64.deb"

      if [ ! -f $SPLUNK_FORWARDER_DEB ]; then
        curl -o $SPLUNK_FORWARDER_DEB https://download.splunk.com/products/universalforwarder/releases/9.4.0/linux/splunkforwarder-9.4.0-6b4ebe426ca6-linux-amd64.deb
      fi

      dpkg -i $SPLUNK_FORWARDER_DEB || apt-get install -f -y

      /opt/splunkforwarder/bin/splunk start --accept-license --answer-yes --no-prompt
      /opt/splunkforwarder/bin/splunk enable boot-start --accept-license --no-prompt
      /opt/splunkforwarder/bin/splunk add forward-server localhost:9997 -auth admin:changeme123 --no-prompt
      /opt/splunkforwarder/bin/splunk restart --no-prompt
    SHELL
  end
end